AndcultureCode/AndcultureCode

RELEASES-TEMPLATE.md, RELEASES.md
Documentation around repository agnostic github release creation.
=> Github releases documentation

.vscode/csharp.code-snippets
Add vscode file for c# snippets, as well as include one for generating a region block with matching comments.
- [- ] Related GitHub issue(s) linked in PR description
=> add file for vscode c sharp snippets

CLEAN-CODE.md
- [n/a] Related GitHub issue(s) linked in PR description
- [n/a] Destination branch merged, built and tested with your changes
- [n/a] Code builds cleanly (no _additional_ warnings or errors)
- [n/a] Documentation updated (readme, docs, comments, etc.)
=> Clean Code initial documentation template

CLEAN-CODE.md
Copy over skeleton of Clean Code markdown file and add section for gratuitous & meaningful context
Closes #27 Book Club: Document our use of "Clean Code: Add meaningful context / Don’t add gratuitous context"
- [-] Destination branch merged, built and tested with your changes
=> Clean Code / Meaningful Names / Don't Add Gratuitous Context & Add Meaningful Context

CLEAN-CODE.md
Closes https://github.com/AndcultureCode/AndcultureCode/issues/25
- [N/A] Code formatted and follows best practices and patterns
- [N/A] Code builds cleanly (no _additional_ warnings or errors)
- [N/A] Manually tested
- [N/A] Automated tests are passing
- [N/A] No _decreases_ in automated test coverage
- [N/A] Localization: No hard-coded error messages in code files (_minimally_ in string constants)
=> Added sections on Class and Method Names in clean code documentation.

CLEAN-CODE.md
- N/A - Code formatted and follows best practices and patterns
- N/A - Code builds cleanly (no _additional_ warnings or errors)
- N/A - Manually tested
- N/A - Automated tests are passing
- N/A - No _decreases_ in automated test coverage
- N/A - Localization: No hard-coded error messages in code files (_minimally_ in string constants)
I've taken some inspiration from this page, https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md, for how to show good and bad practices.  Thoughts?
=> Add "Avoid Encodings" section to clean code doc (Issue #24)

clean-code/FUNCTIONS.md
=> Write up of issue #43 'How Do You Write Functions Like This?'

clean-code/FUNCTIONS.md
#38 Document use of function arguments as determined by Clean Code.
- [/] Code builds cleanly (no _additional_ warnings or errors)
- [/] Manually tested
- [/] Automated tests are passing
- [/] No _decreases_ in automated test coverage
- [/] Localization: No hard-coded error messages in code files (_minimally_ in string constants)
=> #38 Document use of function arguments

clean-code/FUNCTIONS.md
https://github.com/AndcultureCode/AndcultureCode/issues/37
[x] Related GitHub issue(s) linked in PR description
[x] Destination branch merged, built and tested with your changes
[x] Code formatted and follows best practices and patterns
[x] Manually tested
[x] Documentation updated (readme, docs, comments, etc.)
[n/a] Code builds cleanly (no _additional_ warnings or errors)
[n/a] Automated tests are passing
[n/a] No _decreases_ in automated test coverage
[n/a] Localization: No hard-coded error messages in code files (_minimally_ in string constants)
=> Clean Code: Functions: Descriptive Names

clean-code/FUNCTIONS.md
=> Issue #40 - document use of Functions - Command Query Separation

clean-code/FUNCTIONS.md
Resolves #35 Book Club: Document our use of "Clean Code: Functions - One level of abstraction per function"
=> Clean code/one level of abstraction

clean-code/FUNCTIONS.md
Prefer Exceptions to Returning Error Codes for https://github.com/AndcultureCode/AndcultureCode/issues/41
[x] Related GitHub issue(s) linked in PR description
[x] Destination branch merged, built and tested with your changes
[x] Code formatted and follows best practices and patterns
[x] Code builds cleanly (no _additional_ warnings or errors)
[x] Manually tested
[x] No _decreases_ in automated test coverage
=> Prefer Exceptions to Returning Error Codes

clean-code/FUNCTIONS.md
Issue #42 - Book Club: Document our use of Clean Code: Functions - Structured Programming
Brief overview of our opinions regarding structured programming, with an example.
- [x ] Related GitHub issue(s) linked in PR description
- [ x] Destination branch merged, built and tested with your changes
- [ x] Code formatted and follows best practices and patterns
- [ /] Code builds cleanly (no _additional_ warnings or errors)
- [/ ] Manually tested
- [/ ] Automated tests are passing
- [/ ] No _decreases_ in automated test coverage
- [x ] Documentation updated (readme, docs, comments, etc.)
- [ /] Localization: No hard-coded error messages in code files (_minimally_ in string constants)
=> Document our use of Clean Code: Functions - Structured Programming

clean-code/FUNCTIONS.md
Closes #33, closes #34.
- [NA] Code builds cleanly (no _additional_ warnings or errors)
- [NA] Manually tested
- [NA] Automated tests are passing
- [NA] No _decreases_ in automated test coverage
- [NA] Localization: No hard-coded error messages in code files (_minimally_ in string constants)
=> Added documentation for Clean Code - Functions, for the Small and Do One Thing Sections

CLEAN-CODE.md, clean-code/COMMENTS.md
=> Chapter 4: Comments - Comments Do Not Make Up for Bad Code

clean-code/FUNCTIONS.md
- [n/a] No decreases in automated test coverage
- [n/a ] Localization: No hard-coded error messages in code files (_minimally_ in string constants)
Resolves #39 and adds a section to the FUNCTIONS doc for 'Have no side effects'
=> Add 'Have no side effects' section to FUNCTIONS doc

clean-code/COMMENTS.md
https://github.com/AndcultureCode/AndcultureCode/issues/55
[x] Related GitHub issue(s) linked in PR description
[x] Destination branch merged, built and tested with your changes
[x] Code formatted and follows best practices and patterns
[x] Manually tested
[x] Documentation updated (readme, docs, comments, etc.)
=> Bad Comment documentation added

clean-code/FUNCTIONS.md
Fixes issue #36
- [n/a] Code builds cleanly (no _additional_ warnings or errors)
=> Clean Code > Functions - switch statements

clean-code/MEANINGFUL-NAMES.md
Closes #22 
- [NA] Code builds cleanly (no _additional_ warnings or errors)
- [NA] Manually tested
- [NA] Automated tests are passing
- [NA] No _decreases_ in automated test coverage
- [NA] Localization: No hard-coded error messages in code files (_minimally_ in string constants)
=> Added intention revealing names to the meaningful names documentation.

clean-code/COMMENTS.md
#54 Documentation for instances of good comments per 'Clean Code' discussion
- [n/a] Code builds cleanly (no _additional_ warnings or errors)
- [n/a] Manually tested
=> #54 Good Comments

clean-code/COMMENTS.md
Closes #53 Book Club: Document our use of "Clean Code: Comments - Explain Yourself in Code"
- [-] Documentation updated (readme, docs, comments, etc.)
=> Clean Code - Comments - Explain Yourself in Code

clean-code/FORMATTING.md
Add FORMATTING.md with stubbed out sections, fill in Horizontal > General section
Resolves #69 Book Club: Document our use of "Clean Code: Formatting - Horizontal Formatting - General"
- [-] Documentation updated (readme, docs, comments, etc.)
=> Clean Code - Horizontal Formatting - General

clean-code/FORMATTING.md
=> Clean code: Formatting - Team Rules

clean-code/COMMENTS.md, clean-code/FORMATTING.md
https://github.com/AndcultureCode/AndcultureCode/issues/67
[x] Related GitHub issue(s) linked in PR description
[x] Code formatted and follows best practices and patterns
[x] Manually tested
[x] Documentation updated (readme, docs, comments, etc.)
=> Clean Code: Formatting: Vertical Formatting: General

clean-code/COMMENTS.md, clean-code/FORMATTING.md
Book Club: Document our use of "Clean Code: Formatting - Horizontal Formatting - Alignment" #70
=> #70 Horizontal Formatting

clean-code/FORMATTING.md
=> Clean code: Vertical Formatting - Ordering - Issue #68

clean-code/FORMATTING.md
=> Issue 71 clean code formatting horizontal formatting indentation

clean-code/OBJECTS-AND-DATA-STRUCTURES.md
Fixes #82 Book Club: Document our use of "Clean Code: Objects and Data Structures - Data Transfer Objects" 
- [-] Documentation updated (readme, docs, comments, etc.)
=> Clean Code: Objects and Data Structures - Data Transfer Objects

clean-code/ERROR-HANDLING.md
=> Issue #98 - Documenting clean code writing your try/catch/finally first

CLEAN-CODE.md, clean-code/ERROR-HANDLING.md
#97 Documentation for the first section of Clean Code / Exceptions
- [/] Code builds cleanly (no _additional_ warnings or errors)
- [/] Manually tested
- [/] Automated tests are passing
- [/] No _decreases_ in automated test coverage
- [/] Localization: No hard-coded error messages in code files (_minimally_ in string constants)
=> Docs and example for Error handling/exceptions vs error codes

clean-code/BOUNDARIES.md
Resolves #109 Book Club: Document our use of "Clean Code: Boundaries: Learning Boundaries & Tests" 
=> Add Learning Boundaries & Tests section

clean-code/BOUNDARIES.md
=> Clean Code: Boundaries: Using Third-Party Code

clean-code/OBJECTS-AND-DATA-STRUCTURES.md
#80 Added documentation surrounding our use of Data Structures and Objects, and how they relate to their nature asymmetry of each other.
=> added data structure object anti-symmetry documentation

clean-code/BOUNDARIES.md
Resolves #110 
- [/] Code formatted and follows best practices and patterns
- [/] Code builds cleanly (no _additional_ warnings or errors)
- [ /] Automated tests are passing
- [ /] No _decreases_ in automated test coverage
- [ x] Documentation updated (readme, docs, comments, etc.)
- [ /] Localization: No hard-coded error messages in code files (_minimally_ in string constants)
=> Add documentation for unknown code boundaries
